spring:
  # 环境 dev|test|prod
  profiles:
    active: cui
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      enabled: true

FTP:
  ADDRESS: 39.97.250.88
  PORT: 21
  USERNAME: ftpuser
  PASSWORD: ftpuser
  BASEPATH: /home/ftpuser/www
  BASEURL: http://39.97.250.88
